const { Router } = require('express')
const cubeController = require('../controllers/cubes')
const accessoryController = require('../controllers/accessories')
const authController = require('../controllers/authentication')
const auth = require('../utils/auth')
const router = Router()

router.get('/', auth(false), cubeController.getIndex)
router.post('/', auth(false), cubeController.postIndex)
router.get('/about', auth(false), cubeController.about)
router.get('/create', auth(), cubeController.getCreate)
router.post('/create', auth(), cubeController.postCreate)
router.get('/details/:id', auth(), cubeController.getDetails)
router.get('/attach/accessories/:id', auth(), cubeController.getAttachAccessories)
router.post('/attach/accessories/:id', auth(), cubeController.postAttachAccessories)
router.get('/create/accessory', auth(), accessoryController.getCreateAccessory)
router.post('/create/accessory', auth(), accessoryController.postCreateAccessory)
router.get('/accessories', auth(), accessoryController.getAccessories)
router.get('/login', authController.login)
router.post('/login', authController.loginPost)
router.get('/register', authController.register)
router.post('/register', authController.registerPost)
router.get('/logout', auth(), authController.logout)
router.get('/edit/:id', auth(), cubeController.edit)
router.post('/edit/:id', auth(), cubeController.editPost)
router.get('/delete/:id', auth(), cubeController.remove)
router.post('/delete/:id', auth(), cubeController.removePost)
router.get('/passchange/', auth(), authController.getPassChange)
router.post('/passchange/', auth(), authController.postPassChange)
router.all('*', cubeController.notFound)

module.exports = router